# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: go-hello-world"
# - Pod exposes port 8082
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello2
  template:
    metadata:
      labels:
        app: hello2
    spec:
      containers:
      - name: server
        image: asia-south1-docker.pkg.dev/hbl-poc-digfac-anthos-prj/mb-devops/myimage002
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        readinessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 5
